# permissions for end users to edit archimedesproperties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: archimedesproperty-editor-role
rules:
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties/status
  verbs:
  - get
