# permissions for end users to view archimedesproperties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: archimedesproperty-viewer-role
rules:
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties/status
  verbs:
  - get
