
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - backwoods.backwoods-devops.io
  resources:
  - archimedesproperties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backwoods.backwoods-devops.io
  resources:
  - archimedesproperties/finalizers
  verbs:
  - update
- apiGroups:
  - backwoods.backwoods-devops.io
  resources:
  - archimedesproperties/status
  verbs:
  - get
  - patch
  - update
