
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties/finalizers
  verbs:
  - update
- apiGroups:
  - archimedes.backwoods-devops.io
  resources:
  - archimedesproperties/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  - ""
  resources:
  - configmaps
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
