apiVersion: archimedes.backwoods-devops.io/v1
kind: ArchimedesProperty
metadata:
  name: archimedesproperty-sample
spec:
  configMapName: app-properties
  repoUrl: "https://github.com/backwoods-devops/archimedes.git"
  revision: main
  propertiesPath: config/samples/properties.tpl
  sourceConfig: |
    env:
      name: staging
      dbname: forest-data
      dbport: 5432
  propertyType: key
  keyName: config.properties
