{{ if and .Values.rbac.create (eq .Values.archimedes.authMethod "kubernetes") }}
apiVersion: rbac.authorization.k8s.io/v1
kind:  ClusterRole
metadata:
  name: archimedes-property-operator-{{ .Release.Namespace }}
  labels:
{{ include "archimedes-property-operator.labels" . | indent 4 }}
rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - authorization.k8s.io
    resources:
    - subjectaccessreviews
    verbs:
    - create
{{ end }}
