{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if not .Values.rbac.namespaced -}} Cluster {{- end -}} RoleBinding
metadata:
  name: {{ template "archimedes-property-operator.fullname" . }}
  labels:
{{ include "archimedes-property-operator.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if not .Values.rbac.namespaced -}} Cluster {{- end -}} Role
  name: archimedes-property-operator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ template "archimedes-property-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{ end }}
