{{ if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "archimedes-property-operator.fullname" . }}
  labels:
{{ include "archimedes-property-operator.labels" . | indent 4 }}
{{- if .Values.serviceMonitor.labels }}
  {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
{{- end }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      port: http-metrics
      path: "/metrics"
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
  jobLabel: "archimedes-property-operator"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "archimedes-property-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{ end }}
